name: Deploy Node Application

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t kumarsubrato/talkbook-backend  .
      - name: Publish Image to docker hub
        run: docker push kumarsubrato/talkbook-backend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull kumarsubrato/talkbook-backend:latest 
      - name: Delete old container
        run: docker rm -f talkbook-backend-container-ec2 
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name talkbook-backend-container-ec2 kumarsubrato/talkbook-backend:latest